### ISSUE TITLE
how to start on boot

### ISSUE THREAD

**Issue by grenzionky** [r0adrunner/Space2Ctrl#12]
how can i make this start up on boot? i tried putting `s2cctl start` in .xinitrc, and in a script that runs on startup, but it doesnt start… any help?

**Comment by r0adrunner** [comment]
Are you using the full path to s2cctl? Maybe the code in your .xinitrc 
gets executed before setting the PATH.

**Comment by grenzionky** [comment]
I tried it withethe full path too. I just put it into a startup script with `(sleep 5s && s2cctl start) &` and that worked 🤷‍♂

**Comment by r0adrunner** [comment]
closing
