### ISSUE TITLE
Not anymore in AUR

### ISSUE THREAD

**Issue by michalrus** [r0adrunner/Space2Ctrl#8]
`README.md` says:

> Space2Ctrl is currently available via the Arch User Repository (AUR) as 'space2ctrl-git'.

This is no longer true (after AUR4, possibly?).

**Comment by michalrus** [comment]
If anyone is interested, the old `PKGBUILD` is available here, https://web.archive.org/web/20150806145935/https://aur.archlinux.org/packages/sp/space2ctrl-git/PKGBUILD.

**Comment by philipp-classen** [comment]
Fixed. I uploaded the old version to AUR4.

**Comment by michalrus** [comment]
@philipp-classen, thank you. :heart:
